Upgrade to .NET 7, enable WASM optimizations (#173)
* Fixed build errors caused by .NET 7 upgrade

* Updated tooling pointer

Update tooling to latest upgrade/net7

* Bump uno-check

* Skip vswinworkloads

* Update Build Script to support Pull Request Packages Again

Cleaned up some logic for diagnostic builds as well so we have a single build command

* Update tooling to use maccatalyst

* Fix for net7.0-maccatalyst, use dotnet 7.0.100

* Update tooling, additional net7-mobile error suppression

* Update tooling: More error suppression for net7 mobile

* Fixed invalid symbol references in comments

* Update editorconfig

* Update editorconfig

* Update logic for Versioning of Build and ensure to pass to Packing Script

* Use net7.0-android33.0 instead of net7.0-android

* Fix and un-suppress CS1574 errors

* Remove suppression of CS1587

* Update tooling pointer

* Fixed remaining build errors

* Update tooling to latest main

* Suppress CS1587

* Move platfiorm conditionals  to using statements

* Fix issue with XML comment for StackedNotificationsBehavior

2023-08-17T20:08:53.7233918Z      5>D:\a\Windows\Windows\components\Behaviors\src\Notification\StackedNotificationsBehavior.cs(16,70): error CS1574: XML comment has cref attribute 'InfoBar' that could not be resolved

---------

Co-authored-by: michael-hawker <24302614+michael-hawker@users.noreply.github.com>